/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package plantalog;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import plantalog.ImageChooser;
import plantalog.models.Plant;
import plantalog.models.PlantImage;

/**
 *
 * @author Simon
 */
public class addPlant extends javax.swing.JPanel {

    /**
     * Creates new form addPlant
     */
    public addPlant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sci_nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cultivarField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        com_nameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesField = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        plantImageChooser = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        imageCaption = new javax.swing.JTextField();

        jLabel1.setText("Add Plant");

        sci_nameField.setToolTipText("Enter the scientific name of the plant");

        jLabel2.setText("Scientific Name");

        jLabel3.setText("Common Name");

        cultivarField.setToolTipText("Enter the cultivar of the plant");
        cultivarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cultivarFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Cultivar");

        com_nameField.setToolTipText("Enter the common name of the plant");

        jLabel5.setText("Notes");

        notesField.setColumns(18);
        notesField.setRows(4);
        notesField.setToolTipText("Enter any notes relating to the plant");
        jScrollPane1.setViewportView(notesField);

        saveButton.setText("Save");
        saveButton.setToolTipText("Press to save plant");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Image");

        plantImageChooser.setText("Select image...");
        plantImageChooser.setToolTipText("Press to select an image to upload");
        plantImageChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plantImageChooserMouseClicked(evt);
            }
        });
        plantImageChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantImageChooserActionPerformed(evt);
            }
        });

        jLabel7.setText("Image Caption");

        imageCaption.setToolTipText("Enter a caption for the image (if adding an image)");
        imageCaption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageCaptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(81, 81, 81)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(com_nameField)
                                    .addComponent(cultivarField)
                                    .addComponent(sci_nameField)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(saveButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(70, 70, 70)
                                            .addComponent(plantImageChooser))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(imageCaption, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sci_nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cultivarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(com_nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantImageChooser)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageCaption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cultivarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cultivarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cultivarFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(Plantalog.main != null){
            String plant_id = Plant.add(cultivarField.getText(), sci_nameField.getText(), com_nameField.getText(), notesField.getText());
            File image = ImageChooser.getSelectedFile();
            try {
                PlantImage.add(image, plant_id, imageCaption.getText());
            } catch (IOException ex) {
                Logger.getLogger(addPlant.class.getName()).log(Level.SEVERE, null, ex);
            }
            cultivarField.setText("");
            sci_nameField.setText("");
            com_nameField.setText("");
            notesField.setText("");
            imageCaption.setText("");
            
            Plantalog.main.setCard("search");
            Plantalog.main.refreshPlantSearchPane();
        }
            
    }//GEN-LAST:event_saveButtonActionPerformed

    private void plantImageChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantImageChooserActionPerformed
        ImageChooser.showImageChooser(this);
    }//GEN-LAST:event_plantImageChooserActionPerformed

    private void plantImageChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plantImageChooserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_plantImageChooserMouseClicked

    private void imageCaptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageCaptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageCaptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField com_nameField;
    private javax.swing.JTextField cultivarField;
    private javax.swing.JTextField imageCaption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea notesField;
    private javax.swing.JButton plantImageChooser;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField sci_nameField;
    // End of variables declaration//GEN-END:variables
}
