
package plantalog;

import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.imgscalr.Scalr;
import plantalog.models.Plant;
import plantalog.models.PlantImage;
import plantalog.models.Specimen;
import plantalog.models.SpecimenRegion;
import plantalog.models.User;

/**
 * Handles all user interactions for the business activities
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cards = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        addUser = new plantalog.addUser();
        registerNewUser1 = new plantalog.registerNewUser();
        addRegion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addRegionNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addRegionDescTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        addRegionSaveButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        regionSearchTextField = new javax.swing.JTextField();
        regionFilterButton = new javax.swing.JButton();
        regionSearchResultsPane = new javax.swing.JScrollPane();
        regionSearchResults = new javax.swing.JList();
        plantSearchResultsPane = new javax.swing.JScrollPane();
        plantSearchResults = new javax.swing.JList();
        plantSearchTextField = new javax.swing.JTextField();
        plantFilterButton = new javax.swing.JButton();
        specimenFilterButton = new javax.swing.JButton();
        specimenSearchResultsPane = new javax.swing.JScrollPane();
        specimenSearchResults = new javax.swing.JList();
        regionActionsPanel = new javax.swing.JPanel();
        regionActionsLabel = new javax.swing.JLabel();
        deleteRegionButton = new javax.swing.JButton();
        editRegionButton = new javax.swing.JButton();
        plantActionsPanel = new javax.swing.JPanel();
        plantActionsLabel = new javax.swing.JLabel();
        editPlantButton = new javax.swing.JButton();
        deletePlantButton = new javax.swing.JButton();
        specimenActionsPanel = new javax.swing.JPanel();
        specimenActionsLabel = new javax.swing.JLabel();
        editSpecimenButton = new javax.swing.JButton();
        deleteSpecimenButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        specimenName = new javax.swing.JLabel();
        specimenNotes = new javax.swing.JLabel();
        plantNotes = new javax.swing.JLabel();
        mainImage = new javax.swing.JLabel();
        ImageListScrollPane = new javax.swing.JScrollPane();
        imagesList = new javax.swing.JList();
        mainImageCaption = new javax.swing.JLabel();
        numViews = new javax.swing.JLabel();
        addPlant = new plantalog.addPlant();
        addSpecimen = new plantalog.addSpecimen();
        editRegion = new plantalog.editRegion();
        editSpecimen = new plantalog.editSpecimen();
        editPlant = new plantalog.editPlant();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        greeting = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        search = new javax.swing.JButton();
        addRegionButton = new javax.swing.JButton();
        addPlantButton = new javax.swing.JButton();
        addSpecimenButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        statusBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plantlog - Plant Catalog");
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/plantalog/plantalog.png"))).getImage());
        setMinimumSize(new java.awt.Dimension(747, 532));

        cards.setLayout(new java.awt.CardLayout());

        loginPanel.setPreferredSize(new java.awt.Dimension(690, 418));
        loginPanel.setRequestFocusEnabled(false);

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        usernameField.setToolTipText("Enter your username");
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.setToolTipText("Enter your password");

        loginButton.setText("Login");
        loginButton.setToolTipText("Press to login");
        getRootPane().setDefaultButton(loginButton);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setText("Register");
        registerButton.setToolTipText("Press to register a new user");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerButton)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addComponent(passwordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(usernameLabel)
                                .addGap(8, 8, 8)))
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton)
                .addGap(30, 30, 30)
                .addComponent(registerButton)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        cards.add(loginPanel, "login");
        cards.add(addUser, "addUser");
        cards.add(registerNewUser1, "registerNewUser");

        jLabel1.setText("Add Region");

        addRegionNameTextField.setToolTipText("Enter the name of the region");
        addRegionNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRegionNameTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setLabelFor(addRegionNameTextField);
        jLabel2.setText("Region Name");
        jLabel2.setToolTipText("");

        addRegionDescTextArea.setColumns(20);
        addRegionDescTextArea.setRows(5);
        addRegionDescTextArea.setToolTipText("Enter the description of the region");
        jScrollPane1.setViewportView(addRegionDescTextArea);

        jLabel3.setLabelFor(addRegionDescTextArea);
        jLabel3.setText("Description");
        jLabel3.setToolTipText("");

        addRegionSaveButton.setText("Save");
        addRegionSaveButton.setToolTipText("Press to save region");
        addRegionSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRegionSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addRegionLayout = new javax.swing.GroupLayout(addRegion);
        addRegion.setLayout(addRegionLayout);
        addRegionLayout.setHorizontalGroup(
            addRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRegionLayout.createSequentialGroup()
                .addGroup(addRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRegionLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(addRegionLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(addRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addRegionSaveButton)
                            .addGroup(addRegionLayout.createSequentialGroup()
                                .addGroup(addRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(addRegionNameTextField))))))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        addRegionLayout.setVerticalGroup(
            addRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRegionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(addRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRegionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(addRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addComponent(addRegionSaveButton)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        cards.add(addRegion, "addRegion");

        regionSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionSearchTextFieldActionPerformed(evt);
            }
        });

        regionFilterButton.setText("Filter");
        regionFilterButton.setToolTipText("");
        regionFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionFilterButtonActionPerformed(evt);
            }
        });

        regionSearchResults.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        regionSearchResults.setToolTipText("");
        regionSearchResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultOnClick(evt);
            }
        });
        regionSearchResultsPane.setViewportView(regionSearchResults);

        plantSearchResults.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        plantSearchResults.setToolTipText("");
        plantSearchResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plantSearchResultsresultOnClick(evt);
            }
        });
        plantSearchResultsPane.setViewportView(plantSearchResults);

        plantSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantSearchTextFieldActionPerformed(evt);
            }
        });

        plantFilterButton.setText("Filter");
        plantFilterButton.setToolTipText("");
        plantFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantFilterButtonActionPerformed(evt);
            }
        });

        specimenFilterButton.setText("Load");
        specimenFilterButton.setToolTipText("");
        specimenFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specimenFilterButtonActionPerformed(evt);
            }
        });

        specimenSearchResults.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        specimenSearchResults.setToolTipText("");
        specimenSearchResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                specimenSearchResultsresultOnClick(evt);
            }
        });
        specimenSearchResultsPane.setViewportView(specimenSearchResults);

        regionActionsPanel.setPreferredSize(new java.awt.Dimension(143, 100));

        regionActionsLabel.setText("Region Actions");
        regionActionsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regionActionsLabel.setMaximumSize(new java.awt.Dimension(112, 16));
        regionActionsLabel.setMinimumSize(new java.awt.Dimension(112, 16));

        deleteRegionButton.setText("Delete Region");
        deleteRegionButton.setMaximumSize(new java.awt.Dimension(148, 29));
        deleteRegionButton.setMinimumSize(new java.awt.Dimension(148, 29));
        deleteRegionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRegionButtonActionPerformed(evt);
            }
        });

        editRegionButton.setText("Edit Region");
        editRegionButton.setMaximumSize(new java.awt.Dimension(148, 29));
        editRegionButton.setMinimumSize(new java.awt.Dimension(148, 29));
        editRegionButton.setPreferredSize(new java.awt.Dimension(131, 29));
        editRegionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRegionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regionActionsPanelLayout = new javax.swing.GroupLayout(regionActionsPanel);
        regionActionsPanel.setLayout(regionActionsPanelLayout);
        regionActionsPanelLayout.setHorizontalGroup(
            regionActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regionActionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regionActionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(regionActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(regionActionsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(deleteRegionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(regionActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(regionActionsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(editRegionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        regionActionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteRegionButton, editRegionButton, regionActionsLabel});

        regionActionsPanelLayout.setVerticalGroup(
            regionActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regionActionsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(regionActionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(regionActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regionActionsPanelLayout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .addComponent(deleteRegionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(regionActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(regionActionsPanelLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(editRegionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        plantActionsLabel.setText("Plant Actions");
        plantActionsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        plantActionsLabel.setMaximumSize(new java.awt.Dimension(112, 16));
        plantActionsLabel.setMinimumSize(new java.awt.Dimension(112, 16));
        plantActionsLabel.setPreferredSize(new java.awt.Dimension(95, 16));

        editPlantButton.setText("Edit Plant");
        editPlantButton.setMaximumSize(new java.awt.Dimension(148, 29));
        editPlantButton.setMinimumSize(new java.awt.Dimension(148, 29));
        editPlantButton.setPreferredSize(new java.awt.Dimension(131, 29));
        editPlantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPlantButtonActionPerformed(evt);
            }
        });

        deletePlantButton.setText("Delete Plant");
        deletePlantButton.setMaximumSize(new java.awt.Dimension(148, 29));
        deletePlantButton.setMinimumSize(new java.awt.Dimension(148, 29));
        deletePlantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlantButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plantActionsPanelLayout = new javax.swing.GroupLayout(plantActionsPanel);
        plantActionsPanel.setLayout(plantActionsPanelLayout);
        plantActionsPanelLayout.setHorizontalGroup(
            plantActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantActionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plantActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantActionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPlantButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletePlantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        plantActionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deletePlantButton, editPlantButton, plantActionsLabel});

        plantActionsPanelLayout.setVerticalGroup(
            plantActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plantActionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantActionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editPlantButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletePlantButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        specimenActionsPanel.setPreferredSize(new java.awt.Dimension(143, 100));

        specimenActionsLabel.setText("Specimen Actions");
        specimenActionsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        specimenActionsLabel.setPreferredSize(new java.awt.Dimension(95, 16));

        editSpecimenButton.setText("Edit Specimen");
        editSpecimenButton.setMaximumSize(new java.awt.Dimension(148, 29));
        editSpecimenButton.setMinimumSize(new java.awt.Dimension(148, 29));
        editSpecimenButton.setPreferredSize(new java.awt.Dimension(131, 29));
        editSpecimenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSpecimenButtonActionPerformed(evt);
            }
        });

        deleteSpecimenButton.setText("Delete Specimen");
        deleteSpecimenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSpecimenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout specimenActionsPanelLayout = new javax.swing.GroupLayout(specimenActionsPanel);
        specimenActionsPanel.setLayout(specimenActionsPanelLayout);
        specimenActionsPanelLayout.setHorizontalGroup(
            specimenActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specimenActionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(specimenActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specimenActionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSpecimenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSpecimenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        specimenActionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteSpecimenButton, editSpecimenButton, specimenActionsLabel});

        specimenActionsPanelLayout.setVerticalGroup(
            specimenActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specimenActionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(specimenActionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(editSpecimenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteSpecimenButton)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel4.setText("Region");

        jLabel5.setText("Plant Type");

        jLabel6.setText("Specimen");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(searchPanelLayout.createSequentialGroup()
                            .addComponent(regionSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regionFilterButton))
                        .addComponent(regionSearchResultsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(plantSearchResultsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(searchPanelLayout.createSequentialGroup()
                            .addComponent(plantSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plantFilterButton)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(specimenSearchResultsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specimenFilterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regionActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specimenActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        searchPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {plantActionsPanel, regionActionsPanel, specimenActionsPanel});

        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(regionActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plantActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(specimenActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regionSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(regionFilterButton)
                                .addComponent(plantSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plantFilterButton)
                                .addComponent(specimenFilterButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(plantSearchResultsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(regionSearchResultsPane)
                            .addComponent(specimenSearchResultsPane))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        searchPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {plantActionsPanel, regionActionsPanel, specimenActionsPanel});

        cards.add(searchPanel, "search");

        mainPanel.setPreferredSize(new java.awt.Dimension(690, 418));

        specimenName.setToolTipText("");

        mainImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainImage.setToolTipText("");
        mainImage.setAlignmentX(0.5F);
        mainImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mainImage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mainImage.setIconTextGap(0);

        imagesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        imagesList.setToolTipText("");
        imagesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagesListresultOnClick(evt);
            }
        });
        ImageListScrollPane.setViewportView(imagesList);

        mainImageCaption.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mainImageCaption.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        numViews.setToolTipText("");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specimenName, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specimenNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numViews, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(ImageListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainImageCaption, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(specimenName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(plantNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(specimenNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(numViews, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(mainImage, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImageListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(mainImageCaption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        cards.add(mainPanel, "main");

        addPlant.setFocusCycleRoot(true);
        addPlant.setFocusTraversalPolicyProvider(true);
        addPlant.setMinimumSize(null);
        addPlant.setName(""); // NOI18N
        cards.add(addPlant, "addPlant");
        cards.add(addSpecimen, "addSpecimen");
        cards.add(editRegion, "editRegion");
        cards.add(editSpecimen, "editSpecimen");
        cards.add(editPlant, "editPlant");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plantalog/logo.png"))); // NOI18N

        logoutButton.setText("Logout");
        logoutButton.setVisible(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        search.setText("Search New");
        search.setToolTipText("");
        search.setVisible(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        addRegionButton.setText("Add Region");
        addRegionButton.setToolTipText("");
        addRegionButton.setVisible(false);
        addRegionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRegionButtonActionPerformed(evt);
            }
        });

        addPlantButton.setText("Add Plant");
        addPlantButton.setToolTipText("");
        addPlantButton.setActionCommand("Add Region");
        addPlantButton.setVisible(false);
        addPlantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlantButtonActionPerformed(evt);
            }
        });

        addSpecimenButton.setText("Add Specimen");
        addSpecimenButton.setToolTipText("");
        addSpecimenButton.setVisible(false);
        addSpecimenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSpecimenButtonActionPerformed(evt);
            }
        });

        addUserButton.setText("Add User");
        addUserButton.setToolTipText("");
        addUserButton.setVisible(false);
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(37, 37, 37)
                .addComponent(search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addRegionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPlantButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addSpecimenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addSpecimenButton)
                            .addGroup(headerLayout.createSequentialGroup()
                                .addComponent(addRegionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addPlantButton)
                                    .addComponent(addUserButton)))
                            .addComponent(logo))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(search)
                        .addGap(24, 24, 24))))
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton)
                    .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusBar.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 22, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regionFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionFilterButtonActionPerformed
        refreshRegionSearchPane();
        refreshPlantSearchPane();
        refreshSpecimenSearchPane();
    }//GEN-LAST:event_regionFilterButtonActionPerformed
    
    private void resultOnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultOnClick
        refreshPlantSearchPane();
        refreshSpecimenSearchPane();
    }//GEN-LAST:event_resultOnClick

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameField.getText();
        String password = String.valueOf(passwordField.getPassword());
        Plantalog.currentUser = User.login(username, password);
        if(Plantalog.currentUser != null){
            usernameField.setText("");
            passwordField.setText("");
            greeting.setText("Hello " + Plantalog.currentUser.name);
            setCard("search");
            logoutButton.setVisible(true);
            search.setVisible(true);
            refreshRegionSearchPane();
            refreshPlantSearchPane();
            refreshSpecimenSearchPane();
            
            if(Plantalog.currentUser.isEmployee()){ //show employee controls
                addRegionButton.setVisible(true);
                addPlantButton.setVisible(true);
                addSpecimenButton.setVisible(true);
                addUserButton.setVisible(true);
            }
            Plantalog.main.setStatus("Logged in " + Plantalog.currentUser.name);
        }else{
            
            Plantalog.main.setStatus("Error Logging in...");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void regionSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionSearchTextFieldActionPerformed

    private void plantSearchResultsresultOnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plantSearchResultsresultOnClick
        refreshSpecimenSearchPane();
    }//GEN-LAST:event_plantSearchResultsresultOnClick

    private void plantSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantSearchTextFieldActionPerformed

    private void plantFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantFilterButtonActionPerformed
        refreshPlantSearchPane();
        refreshSpecimenSearchPane();
    }//GEN-LAST:event_plantFilterButtonActionPerformed

    private void specimenFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specimenFilterButtonActionPerformed
        Specimen s = (Specimen)this.specimenSearchResults.getSelectedValue();
        if(s != null){
            Plantalog.main.setStatus("Loading Data for " + s.plant.sci_name);
            loadData(s);
            setCard("main");
        }
    }//GEN-LAST:event_specimenFilterButtonActionPerformed

    private void specimenSearchResultsresultOnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specimenSearchResultsresultOnClick
        
    }//GEN-LAST:event_specimenSearchResultsresultOnClick

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        setCard("search");
    }//GEN-LAST:event_searchActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        
        addRegionButton.setVisible(false);
        addPlantButton.setVisible(false);
        addSpecimenButton.setVisible(false);
        addUserButton.setVisible(false);
        Plantalog.currentUser = null;
        logoutButton.setVisible(false);
        search.setVisible(false);
        greeting.setText("");
        setCard("login");
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void imagesListresultOnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagesListresultOnClick
        PlantImage p = (PlantImage)this.imagesList.getSelectedValue();
        if(p != null)
            loadImage(mainImage, p);
        else
            System.out.println("failed to find image selected");
    }//GEN-LAST:event_imagesListresultOnClick

    private void addRegionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRegionButtonActionPerformed
        setCard("addRegion");
        this.addRegionDescTextArea.setText("");
        this.addRegionNameTextField.setText("");
    }//GEN-LAST:event_addRegionButtonActionPerformed

    private void addRegionNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRegionNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRegionNameTextFieldActionPerformed

    private void addRegionSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRegionSaveButtonActionPerformed
        SpecimenRegion.add(addRegionNameTextField.getText(), addRegionDescTextArea.getText());
        setCard("search");
        refreshRegionSearchPane();
    }//GEN-LAST:event_addRegionSaveButtonActionPerformed

    private void addPlantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlantButtonActionPerformed
        setCard("addPlant");
    }//GEN-LAST:event_addPlantButtonActionPerformed

    private void addSpecimenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSpecimenButtonActionPerformed
        this.addSpecimen.refresh();
        setCard("addSpecimen");
    }//GEN-LAST:event_addSpecimenButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        setCard("addUser");
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        setCard("registerNewUser");
    }//GEN-LAST:event_registerButtonActionPerformed

    private void deleteRegionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRegionButtonActionPerformed
        
        SpecimenRegion region = (SpecimenRegion)this.regionSearchResults.getSelectedValue();
        SpecimenRegion.delete(region);
        refreshRegionSearchPane();
        refreshPlantSearchPane();
        refreshSpecimenSearchPane();
    }//GEN-LAST:event_deleteRegionButtonActionPerformed

    private void editRegionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRegionButtonActionPerformed
        setCard("editRegion");
        SpecimenRegion region = (SpecimenRegion)this.regionSearchResults.getSelectedValue();
        editRegion.descriptionField.setText(region.description);
    }//GEN-LAST:event_editRegionButtonActionPerformed

    private void editPlantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPlantButtonActionPerformed
        setCard("editPlant");
        Plant plant = (Plant)this.plantSearchResults.getSelectedValue();
        editPlant.cultivarField.setText(plant.cultivar);
        editPlant.sci_nameField.setText(plant.sci_name);
        editPlant.com_nameField.setText(plant.com_name);
        editPlant.notesField.setText(plant.notes);
        editPlant.imageCaption.setText(plant.images.get(0).caption);
    }//GEN-LAST:event_editPlantButtonActionPerformed

    private void deletePlantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlantButtonActionPerformed
        
        Plant plant = (Plant)this.plantSearchResults.getSelectedValue();
        Plant.delete(plant);
        refreshPlantSearchPane();
        refreshSpecimenSearchPane();
    }//GEN-LAST:event_deletePlantButtonActionPerformed

    private void editSpecimenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSpecimenButtonActionPerformed
        Specimen specimen = (Specimen)this.specimenSearchResults.getSelectedValue();
        editSpecimen.setValues(specimen);
        setCard("editSpecimen");
    }//GEN-LAST:event_editSpecimenButtonActionPerformed

    private void deleteSpecimenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSpecimenButtonActionPerformed
        
        Specimen specimen = (Specimen)this.specimenSearchResults.getSelectedValue();
        Specimen.delete(specimen);
        refreshSpecimenSearchPane();
    }//GEN-LAST:event_deleteSpecimenButtonActionPerformed

    /**
     * Load data for a specimen in the main frame
     * 
     * @param s
     */
    private void loadData(Specimen s){
        this.specimenName.setText(s.plant + " " + s.lives_in);
        this.specimenNotes.setText(s.notes);
        this.plantNotes.setText(s.plant.notes);
        this.numViews.setText("This was viewed: " + s.get_num_views() + " times");
        if(s.plant.images.size() > 0)
            loadImage(mainImage, s.plant.images.get(0));
        else{
            mainImage.setIcon(null);
            mainImage.setText("No images available");
        }
        this.imagesList.setModel(Plantalog.toListModel(s.plant.images));
        DBC.view(s, Plantalog.currentUser);
        Plantalog.main.setStatus("Loaded Data for " + s.plant.sci_name);
    }
    
    private void loadImage(JLabel label, PlantImage pi){
        
        label.setText("Loading...");
        mainImageCaption.setText(pi.caption);
        label.setIcon(null);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BufferedImage i = (BufferedImage)pi.getImage();
                if(i != null){
                    label.setText("");
                    BufferedImage bi = Scalr.resize(i, Scalr.Method.SPEED, Scalr.Mode.FIT_TO_WIDTH,
                            label.getWidth()-4, label.getHeight()-4, Scalr.OP_ANTIALIAS);
                    label.setIcon(new ImageIcon(bi));
                }else{
                    label.setText("Error Loading Image: Invalid URL");
                }
            }
        });
    }
    
    public void setStatus(String status){
        this.statusBar.setText(status);
    }
    
    public void refreshRegionSearchPane(){
        this.regionSearchResults.setModel(Plantalog.toListModel(SpecimenRegion.getRegions(this.regionSearchTextField.getText())));
    }
    public void refreshPlantSearchPane(){
        this.plantSearchResults.setModel(Plantalog.toListModel(Plant.getPlants(this.plantSearchTextField.getText())));
    }
    public void refreshSpecimenSearchPane(){
        SpecimenRegion r = (SpecimenRegion)this.regionSearchResults.getSelectedValue();
        Plant p = (Plant)this.plantSearchResults.getSelectedValue();
        this.specimenSearchResults.setModel(Plantalog.toListModel(Specimen.getSpecimens(r,p)));
    }
    
    public void setCard(String cardname){
        ((CardLayout)this.cards.getLayout()).show(this.cards, cardname);        
    }
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainFrame m = new MainFrame();
                m.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        DBC.disconnect();
                        System.exit(0);
                    }
                });
                m.setVisible(true);
                Plantalog.main = m;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ImageListScrollPane;
    private plantalog.addPlant addPlant;
    private javax.swing.JButton addPlantButton;
    private javax.swing.JPanel addRegion;
    private javax.swing.JButton addRegionButton;
    private javax.swing.JTextArea addRegionDescTextArea;
    private javax.swing.JTextField addRegionNameTextField;
    private javax.swing.JButton addRegionSaveButton;
    private plantalog.addSpecimen addSpecimen;
    private javax.swing.JButton addSpecimenButton;
    private plantalog.addUser addUser;
    private javax.swing.JButton addUserButton;
    private javax.swing.JPanel cards;
    private javax.swing.JButton deletePlantButton;
    private javax.swing.JButton deleteRegionButton;
    private javax.swing.JButton deleteSpecimenButton;
    public plantalog.editPlant editPlant;
    private javax.swing.JButton editPlantButton;
    private plantalog.editRegion editRegion;
    private javax.swing.JButton editRegionButton;
    private plantalog.editSpecimen editSpecimen;
    private javax.swing.JButton editSpecimenButton;
    private javax.swing.JLabel greeting;
    private javax.swing.JPanel header;
    private javax.swing.JList imagesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel mainImage;
    private javax.swing.JLabel mainImageCaption;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel numViews;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel plantActionsLabel;
    private javax.swing.JPanel plantActionsPanel;
    private javax.swing.JButton plantFilterButton;
    private javax.swing.JLabel plantNotes;
    public javax.swing.JList plantSearchResults;
    private javax.swing.JScrollPane plantSearchResultsPane;
    private javax.swing.JTextField plantSearchTextField;
    private javax.swing.JLabel regionActionsLabel;
    private javax.swing.JPanel regionActionsPanel;
    private javax.swing.JButton regionFilterButton;
    public javax.swing.JList regionSearchResults;
    private javax.swing.JScrollPane regionSearchResultsPane;
    private javax.swing.JTextField regionSearchTextField;
    private javax.swing.JButton registerButton;
    private plantalog.registerNewUser registerNewUser1;
    private javax.swing.JButton search;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel specimenActionsLabel;
    private javax.swing.JPanel specimenActionsPanel;
    private javax.swing.JButton specimenFilterButton;
    private javax.swing.JLabel specimenName;
    private javax.swing.JLabel specimenNotes;
    public javax.swing.JList specimenSearchResults;
    private javax.swing.JScrollPane specimenSearchResultsPane;
    private javax.swing.JLabel statusBar;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
